### PR TITLE
Fixed Issue #86

### PR DESCRIPTION
**Pull request by haidangwa**
Fixes tidy_server_clean Issue #86

### CODE REVIEW

**Comment by haidangwa** [comment]
The travis failure are pre-existing failures

**Comment by tas50** [comment]
@haidangwa Any chance you an break out just the fix here since I cleaned up all the testing / specs stuff for the 2.x release?

**Comment by haidangwa** [comment]
@tas50 Thanks, I'll look into this

**Comment by haidangwa** [comment]
@tas50 the build is failing on chefspecs. I didn't touch those.

**Pull request closed without merging**
