### PR TITLE
Fixed --keep-versions to account for node data.

### PR DESCRIPTION
**Pull request by ecottom**
Signed-off-by: ECOTTOM <ECOTTOM@mitre.org>

## Description

The feature that added [keep_versions](96af2f0cd7564b4ca3cb27f2e73fd596ceabb186) seems to ignore the data on the nodes and just creates a report with X most recent cookbooks. It looks like [line 85 of tidy_server_report.rb ](https://github.com/chef/knife-tidy/blob/3d35f05b6e4edbe197ea9415efff60698ae24f52/lib/chef/knife/tidy_server_report.rb#L85) `used_cookbooks = keep_cookbook_versions(cb_list, keep_versions)` resets used_cookbooks using the list of call cookbooks ignoring all of the node data. I updated the logic in `unused_cookbooks` to remove the last keep_versions of cookbooks from the list of unsed cookbooks.

## Related Issue
* [Tidy removing needed/required/used cookbook versions](https://github.com/chef/knife-tidy/issues/131)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
@ecottom any chance you can rebase this now that we've fixed all the testing?

**Comment by ecottom** [comment]
@tas50 it looks like its passing now.

**Comment by vkarve-chef** [comment]
@ecottom could you please discard the `CHANGELOG.md` file from the PR? It will automatically updated by Expeditor in a follow up commit.

**Review by vkarve-chef — APPROVED** [review]

**Comment by vkarve-chef** [comment]
for some reason, am unable to merge this PR. have picked the relevant change into https://github.com/chef/knife-tidy/pull/142 which we will have merged.

**Comment by vkarve-chef** [comment]
merged via https://github.com/chef/knife-tidy/pull/142

**Pull request closed without merging**
